### ISSUE TITLE
question on special keys

### ISSUE THREAD

**Issue by redon** [petrsimon/cordova.externalkeyboard#3]
Hi

I am working on an app for handicapped people and it would be a great use if I could catch the following keys: SPACE, ENTER, KEY UP, KEY DOWN, KEY LEFT, KEY RIGHT
A combination with ctrl etc. would be fine too (I saw that "Single key shortcuts are not supported")

Is it possible to catch those keys?
What would be the shortcuts for them?

I saw that you commented out the Arrows.

Thanks

**Comment by petrsimon** [comment]
Hi,
yes all that should be possible, but it has to be done in Objective-C. If you look into the source code, you'll see that the some of the code (snippets really) for arrow keys, escape and enter is already there, only commented out (see method getCombo in ExternalKeyboard.m).
If you don't know what to do with it, let me know I'll try to help, since it's for such a good cause :)
Cheers

**Comment by redon** [comment]
Hi

thank you for your fast and positive response. I am not really a programmer. I know some javascript and was told how to use cordova and xcode with the help of some bash scripts that were given to me. So Objective-C and how to implement that into the plugin would be quiet a challenge for me.
If you could help me, thank you very much. Otherwise I will find somebody who could do it for me.
If you are interested in our project you find some informations here: www.dob.li

Cheers

**Comment by petrsimon** [comment]
OK. I'll try to do it soon. Can't promise when, but I should have time within a week or two.
Petr

**Comment by redon** [comment]
That would be very fine!
Thank you

**Comment by petrsimon** [comment]
Done. Had some free time, so couldn't resist :) 
I haven't tested it much, though, so please open an issue if something is not working properly. Please see the updated readme.
